kind: ConfigMap
apiVersion: v1
metadata:
  name: alertmanager-conf
  labels:
    name: alertmanager-conf
  namespace: monitoring
data:
  config.yml: |-
    global:
    templates:
    - '/etc/alertmanager/*.tmpl'
    route:
      receiver: alert-emailer
      group_by: ['alertname', 'priority']
      group_wait: 10s
      repeat_interval: 30m
 
    receivers:
    - name: alert-emailer
      email_configs:
      - to: 'ec2-user@localhost'
        send_resolved: false
        from: 'alertmanager@localhost'
        smarthost: 'localhost:25'
        require_tls: false
